[workspace]

members = [
    "core",
    "native",
    "wasm",
]

[workspace.dependencies]
fastcrypto = { git = "https://github.com/MystenLabs/fastcrypto.git", rev = "c412b86", features = ["copy_key"] }
rand = "0.8.5"
hex = "0.4.3"
bincode = "1.3.3"