[workspace]
resolver = "2"

members = [
    "core",
    "native",
    "wasm",
]

[workspace.dependencies]
fastcrypto = { version = "0.1.7", features = ["copy_key"] }
rand = "0.8.5"
hex = "0.4.3"
bincode = "1.3.3"