[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "fastcrypto"
crate-type = ["cdylib"]

[dependencies]
fastcrypto = { git = "https://github.com/MystenLabs/fastcrypto.git" }
rand = "0.8.5"
hex = "0.4.3"
bincode = "1.3.3"
jni = "0.21.0"